title: Zhiyu Kang's Homepage
page-top-title: Zhiyu Kang
top-section-bg-text: Artificial intelligence
home-subtitle: Zhiyu Kang&ensp;|&ensp;康知语
copyright-text: '&copy; Zhiyu Kang 2025. All Rights Reserved.'
